seed: 42
rows: 800

paths:
  data_csv: "data/fragrance_data.csv"
  out_dir: "artifacts"
  predictions_csv: "artifacts/predictions.csv"
  metrics_json: "artifacts/metrics.json"
  reports_dir: "reports"
  figs_dir: "reports/figures"

model:
  estimator: "xgb"
  xgb:
    n_estimators: 600
    max_depth: 5
    learning_rate: 0.05
    colsample_bytree: 0.9
    min_child_weight: 2
    n_jobs: 0
    eval_metric: "auc"
  lgbm:
    n_estimators: 800
    num_leaves: 63
    learning_rate: 0.05
